version: "3.2"
services:
#  database:
#    container_name: mariadb
#    image: mariadb
#    volumes:
#      - /volume1/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
#      - /volume1/docker/mariadb/var/lib/mysql:/var/lib/mysql
#      - /volume1/docker/mariadb/var/log/maria:/var/log/maria
#    environment:
#      - MYSQL_DATABASE=medicalip
#      - MYSQL_ROOT_PASSWORD=medicalip808!
#      - MYSQL_ROOT_HOST=%
#    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
#    ports:
#      - 3333:3306

  application:
    container_name: homepage_backend
    build: .
    volumes:
      - /volume1/docker/homepage_backend/homepage-0.0.1-SNAPSHOT.jar:/home/homepage/springboot/homepage.jar
      
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3333/medicalip?useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: medicalip808!
    ports:
      - 8081:8080
    depends_on:
      - mariadb
